### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by 8Ozymandias** [superapp/react-native-location-view#1]
The code you have provided works for React Native and not for the Android and X code versions of React Native? I am asking because most react-native map code samples and packages relate to the Android and X code versions/forms of React Native.

**Comment by hhunaid** [comment]
I am sorry, I don't understand the question correctly.
Do you mean Google maps for Android and MapKit for iOS?

**Comment by 8Ozymandias** [comment]
Yes.

**Comment by hhunaid** [comment]
I'm afraid we do not support the MapKit for now. You are welcome to fork the project and play around. We do support Google Maps on iOS.

**Comment by HusseinElGanzory** [comment]
> I'm afraid we do not support the MapKit for now. You are welcome to fork the project and play around. We do support Google Maps on iOS.

i think you can add Google Map Provider to MapView it will display google Map 

```
<MapView
          ref={(mapView) => this._map = mapView}
          style={styles.mapView}
          region={this.state.region}
          showsMyLocationButton={true}
          provider={PROVIDER_GOOGLE} // remove if not using Google Maps
          showsUserLocation={true}
          onPress={({nativeEvent}) => this._setRegion(nativeEvent.coordinate)}
          onRegionChange={this._onMapRegionChange}
          onRegionChangeComplete={this._onMapRegionChangeComplete}
        />
```
