### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by praveenganesh** [superapp/react-native-location-view#10]
Error: Unable to resolve module `@react-native-community/geolocation` from `node_modules\react-native-location-view\src\LocationView.js`

**Comment by praveenganesh** [comment]
There is no callback function for search place onChange. autosuggestion, not happening.but you showed that feature in demo

**Comment by hhunaid** [comment]
You need to install `@react-native-community/geolocation` package separately. Since there are multiple versions of these which work for different react native versions AND you need to have this module in your package.json for auto-linking to work.

**Comment by praveenganesh** [comment]
@react-native-community/geolocation this information missing in documentation
