### ISSUE TITLE
Feature missing 

### ISSUE THREAD

**Issue by praveenganesh** [superapp/react-native-location-view#11]
There is no callback function for search place onChange. autosuggestion, not happening.but you showed that feature in demo

**Comment by hhunaid** [comment]
Are you sure you have all the required keys in place?

**Comment by praveenganesh** [comment]
yes

**Comment by yalva** [comment]
Had the same issue when key had only Android and IOS sdk permissions, after enabling Places API its working

**Comment by hhunaid** [comment]
Thanks @yalva. Going to close this now.

**Comment by pruthvirajkarur** [comment]
> There is no callback function for search place onChange. autosuggestion, not happening.but you showed that feature in demo

Were you able to get it? even i am not getting it. If i click on the places from the list is not reflecting on the map.
