### ISSUE TITLE
Geocoding is not working

### ISSUE THREAD

**Issue by yalva** [superapp/react-native-location-view#16]
When we select a location on the map instead of searching for a place, its not bring the place address, name etc.

**Comment by yalva** [comment]
Ok its working after enabling the geocoding API for the key, so for this to working on both iOS and Android one would have to enable  Places API and Geocoding API

Please confirm if we need to enable Android SDK API and iOS SDK API as well?

**Comment by hhunaid** [comment]
You don't need Android or iOS SDK API access because this module doesn't rely on it. Just the Geocoding API will do.
