### ISSUE TITLE
saving lat and lng and address to use it later

### ISSUE THREAD

**Issue by elmarzougui** [superapp/react-native-location-view#4]
i think you should make an example how to save lat and lng for selected or picked place 
i can't find any solution ?

**Comment by hhunaid** [comment]
you can use the `onLocationSelect` prop

**Comment by elmarzougui** [comment]
yes i know but what result i have ? can you give me an example please how can i save it for example in the local state ?

**Comment by elmarzougui** [comment]
> yes i know but what result i have ? can you give me an example please how can i save it for example in the local state ?

        <LocationView
          markerColor='black'
          apiKey={google_map_key}
          initialLocation={{
            latitude: 37.78825,
            longitude: -122.4324,
          }}
          **onLocationSelect={(result) => {
            console.log(result)
          }}**
        />

i find a solution thank you 👌
