### ISSUE TITLE
It  is possible to get Country and City individually ?

### ISSUE THREAD

**Issue by HusseinElGanzory** [superapp/react-native-location-view#5]

**Comment by hhunaid** [comment]
Do you mean in the suggestions?

**Comment by HusseinElGanzory** [comment]
i mean after select location form map

**Comment by hhunaid** [comment]
For now, this information is not sent to the callback. But I think it's fairly simple to do so. You can always open a PR

**Comment by HusseinElGanzory** [comment]
what 's you mean PR ?

**Comment by hhunaid** [comment]
Pull Request. You can edit the code and submit it here.

**Comment by HusseinElGanzory** [comment]
Ok, thanks for you support and for control. i will try to do that isa

**Comment by hhunaid** [comment]
`placeDetails` are added in the latest version.
