### ISSUE TITLE
Not updating current location address on Search bar 

### ISSUE THREAD

**Issue by gugakatsi** [superapp/react-native-location-view#6]
just normal setup nothing special , api key is working fine ( for search bar ) , but when i am moving pin to somewhere else it's not updating location's address on input bar.

**Comment by hhunaid** [comment]
Can you mention RN and RNmaps version you are using?

**Comment by gugakatsi** [comment]
0.59.9 , rn maps 0.24.2

**Comment by hhunaid** [comment]
The library is working for us on rn 0.59.8 and rnmaps 0.24.2
Are you sure you didn't miss a step? If you can upload a reproducible project somewhere I can take a look.

**Comment by gugakatsi** [comment]
I could upload in few hrs, what step could I possible miss ? Because search suggestions would not work right?

**Comment by hhunaid** [comment]
Yes. Only steps are maps and places API setup. It's somewhat strange for me as well.

**Comment by gugakatsi** [comment]
it was api key issue, i enabled Place api as webservice and it worked now, before that i just toggled place api and grabed random api key , api key was not supposed to be for android or ios , but still it was wroking only for search suggestions, right now its working perfectly.
